export const SystemName = "Ecommerce"

export const Regex = {
  PASSWORD:
    /^(?=(.*[a-z]){1,})(?=(.*[A-Z]){1,})(?=(.*[0-9]){1,})(?=(.*['"{}|:;<>,?!@#$%^&*()\-__+.]){1,}).{8,}$/,
  EMAIL: /^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/,
  NUMERICAL: /^[0-9]+$/,
  ALPHA: /^[ A-Za-z'-]*$/,
  ALPHANUMERIC: /^([a-zA-Z0-9 _-]+)$/,
  MONGOOBJECT: /^[0-9a-fA-F]{24}$/,
  SPECIALCHARS: /\W|_/g,
  CSVDOT_HYPHEN: /^[a-zA-Z0-9 .,-:;()&?!']{0,50000000}$/,
  USERNAME: /^[a-zA-Z0-9]+(?:[_-][a-zA-Z0-9]+)?$/,
  ISBASE64:
    /^([A-Za-z0-9+/]{4})*([A-Za-z0-9+/]{4}|[A-Za-z0-9+/]{3}=|[A-Za-z0-9+/]{2}==)$/,
  ISACADEMICYEAR: /^\d{4}-\d{4}$/,
  UNEXPECTED_ATTR: /[^\w\s]/gi,
  WHITESPACES: /\s{2,}/g,
  DECIMAL_NUM: /^\d+(\.\d{1,3})?$/,
  URL: /^(https?|ftp):\/\/(([a-z\d]([a-z\d-]*[a-z\d])?\.)+[a-z]{2,}|localhost)(\/[-a-z\d%_.~+]*)*(\?[;&a-z\d%_.~+=-]*)?(\#[-a-z\d_]*)?$/i,
}

export const Regions = [
  {
    region: "Greater Accra",
    districts: [
      "Accra Central",
      "Ablekuma Central",
      "Ablekuma North",
      "Ablekuma West",
      "Adenta",
      "Agbogbloshie",
      "Ayawaso Central",
      "Ayawaso East",
      "Ayawaso North",
      "Ayawaso West",
      "Dzorwulu",
      "Labone",
      "Madina",
      "Nungua",
      "Tema Central",
      "Tema East",
      "Tema West",
    ],
  },
  {
    region: "Ashanti",
    districts: [
      "Asante Akim North",
      "Asante Akim South",
      "Asokwa",
      "Atwima Kwanwoma",
      "Atwima Mponua",
      "Bekwai",
      "Berekum East",
      "Berekum West",
      "Ejisu",
      "Kumasi North",
      "Kumasi South",
      "Kumasi Central",
      "Mampong",
      "Obuasi East",
      "Obuasi West",
      "Sekyere East",
      "Sekyere South",
    ],
  },
  {
    region: "Western",
    districts: [
      "Axim",
      "Bibiani-Anhwiaso-Bekwai",
      "Bia East",
      "Bia West",
      "Jomoro",
      "Prestea-Huni Valley",
      "Sefwi Akontombra",
      "Sefwi Bekwai",
      "Sefwi Juaboso",
      "Sefwi Wiawso",
      "Shama",
      "Takoradi",
      "Wassa East",
      "Wassa West",
    ],
  },
  {
    region: "Eastern",
    districts: [
      "Abuakwa North",
      "Abuakwa South",
      "Akyemansa",
      "Brewaniase",
      "Donkorkrom",
      "Ekye Amanfrom",
      "Kade",
      "Koforidua",
      "Nkawkaw",
      "Suhum",
      "Wenchi",
      "Yilo Krobo",
      "Akropong",
      "Nsawam-Adoagyiri",
      "Akwatia",
    ],
  },
  {
    region: "Northern",
    districts: [
      "Bimbilla",
      "Chereponi",
      "Gambaga",
      "Gushegu",
      "Karaga",
      "Kumbungu",
      "Mion",
      "Nabdam",
      "Nanton",
      "Nalerigu",
      "Savelugu",
      "Tamale Central",
      "Tamale North",
      "Tamale South",
      "Tatale",
    ],
  },
  {
    region: "Central",
    districts: [
      "Agona East",
      "Agona West",
      "Assin North",
      "Assin South",
      "Cape Coast North",
      "Cape Coast South",
      "Kormantse",
      "Mankessim",
      "Swedru",
      "Twifo Atti-Morkwa",
      "Twifo Hemang Lower Denkyira",
      "Wassa East",
      "Wassa West",
    ],
  },
  {
    region: "Western North",
    districts: [
      "Aowin",
      "Bodi",
      "Bibiani-Anhwiaso-Bekwai",
      "Dabokpa",
      "Sefwi Akontombra",
      "Sefwi Bekwai",
      "Sefwi Juaboso",
      "Sefwi Wiawso",
      "Jomoro",
      "Nzema East",
      "Nzema West",
    ],
  },
  {
    region: "Upper East",
    districts: [
      "Bolgatanga Central",
      "Bolgatanga East",
      "Bolgatanga West",
      "Bawku Central",
      "Bawku East",
      "Bawku West",
      "Garu",
      "Navrongo",
      "Pusiga",
      "Sandema",
      "Tongo",
      "Zebilla",
    ],
  },
  {
    region: "Upper West",
    districts: [
      "Wa East",
      "Wa Municipal",
      "Wa West",
      "Jirapa",
      "Nandom",
      "Nadowli-Kaleo",
      "Sissala East",
      "Sissala West",
      "Lawra",
      "Tumu",
      "Wa",
    ],
  },
  {
    region: "Volta",
    districts: [
      "Aflao",
      "Anlo",
      "Bator",
      "Denu",
      "Ho",
      "Hohoe",
      "Kpando",
      "Sogakope",
      "Tafi Atome",
      "Volta North",
      "Yilo Krobo",
      "Ziope",
    ],
  },
  {
    region: "Oti",
    districts: [
      "Dambai",
      "Nkwanta North",
      "Nkwanta South",
      "Tatale",
      "Bimbilla",
      "Chereponi",
      "Nkonya",
      "Oti",
    ],
  },
  {
    region: "Ahafo",
    districts: [
      "Asunafo North",
      "Asutifi North",
      "Asutifi South",
      "Asunafo South",
      "Tano North",
      "Tano South",
    ],
  },
  {
    region: "Bono",
    districts: [
      "Berekum East",
      "Berekum West",
      "Dormaa East",
      "Dormaa West",
      "Jaman North",
      "Jaman South",
      "Sunyani East",
      "Sunyani West",
    ],
  },
  {
    region: "Bono East",
    districts: [
      "Techiman North",
      "Techiman South",
      "Kintampo North",
      "Kintampo South",
      "Nkoranza North",
      "Nkoranza South",
      "Pru East",
      "Pru West",
      "Tano North",
      "Tano South",
    ],
  },
  {
    region: "Savannah",
    districts: [
      "Bole",
      "Damongo",
      "East Gonja",
      "West Gonja",
      "Sawla-Tuna-Kalba",
      "Central Gonja",
      "North East Gonja",
    ],
  },
]
